version: '3.8'

services:
  simulaaws-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulaaws-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - simulaaws-network
    restart: unless-stopped

  grafana-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: simulaaws-observability
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    networks:
      - simulaaws-network
    restart: unless-stopped

networks:
  simulaaws-network:
    driver: bridge
