spring:
  application:
    name: simulacert-dev

#  datasource:
#    url: jdbc:h2:mem:simulacert
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#  flyway:
#    enabled: false

server:
  port: 8080

app:
  jwt:
    secret: dev-secret-key-simulacert-development-only-not-for-production-64-bytes-minimum-878xxxxx
    expiration: 86400000
  import:
    input-dir: ./data/import/fazer
    processed-dir: ./data/import/feito

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
  writer-with-order-by-keys: true

info:
  app:
    name: simulacert
    version: 1.0.0-DEV
    description: Sistema de Simulados AWS - Development
    architecture: modular-monolith
    profile: dev

logging:
  level:
    root: INFO
    br.com.simulacert: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



