spring:
  application:
    name: auth-service-dev

app:
  jwt:
    secret: dev-secret-key-simulaaws-development-only-not-for-production-64-bytes-minimum-xxxxxxxx
    expiration: 86400000

logging:
  level:
    root: DEBUG
    br.com.simulaaws.auth: DEBUG
    org.springframework.security: DEBUG
