spring:
  application:
    name: stats-service

  datasource:
    url: jdbc:postgresql://localhost:5432/simulaaws
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8084

clients:
  attempt:
    url: http://localhost:8083
  exam:
    url: http://localhost:8082
  auth:
    url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    br.com.simulaaws.stats: INFO
